name = "glen"
version = "2.2.2"
target = "javascript"
description = "A peaceful web framework that targets JS."
licences = ["MIT"]
repository = { type = "github", user = "MystPi", repo = "glen" }

[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
conversation = { git = "git@github.com:MoeDevelops/conversation", ref = "master"}
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
marceau = ">= 1.3.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"

[dev-dependencies]
repeatedly = ">= 2.1.2 and < 3.0.0"
